export type SiteSettings = {
  id: number;
  site_name: string;
  site_description: string;
  meta_title: string;
  meta_keywords: string | null;
  meta_robots: string | null;
  canonical_url: string | null;
  og_title: string | null;
  og_description: string | null;
  og_image_url: string | null;
  logo_url: string | null;
  favicon_url: string | null;
  phone: string;
  email: string;
  whatsapp_phone: string;
  address_street: string | null;
  address_locality: string | null;
  address_region: string | null;
  postal_code: string | null;
  address_country: string | null;
  address_display: string | null;
  contact_page_title: string | null;
  contact_page_subtitle: string | null;
  contact_hub_title: string | null;
  map_embed_url: string | null;
  map_link_url: string | null;
  hours_airport: string | null;
  hours_office: string | null;
  hours_response: string | null;
  hero_badge: string | null;
  hero_title: string | null;
  hero_subtitle: string | null;
  hero_image_url: string | null;
  hero_travelers_label: string | null;
  stat_1_value: string | null;
  stat_1_label: string | null;
  stat_2_value: string | null;
  stat_2_label: string | null;
  stat_3_value: string | null;
  stat_3_label: string | null;
  stat_4_value: string | null;
  stat_4_label: string | null;
  footer_description: string | null;
  cta_title: string | null;
  cta_subtitle: string | null;
  facebook_url: string | null;
  twitter_url: string | null;
  instagram_url: string | null;
  maintenance_mode: boolean;
  maintenance_message: string | null;
  updated_at: string;
};
